export {default as Home} from './Home';
export {default as About} from './About';
export {default as Profile} from './Profile';
export {default as NotFound} from './NotFound';
export {default as IpInfo} from './IpPage';
export {default as TodoPage} from './TodoPage';
export {default as Userpage} from './Userpage';
export {default as DeployPage} from './DeployPage';
export {default as UserPaginationPage} from './UserPaginationPage';
